### ISSUE TITLE
Single GPIO

### ISSUE THREAD

**Issue by bob-u** [JoeyStrandnes/NST1001_Arduino-Driver#2]
Hi

Thanks for making the code available for my favorite temp sensor.  Have you considered implementing readout for single GPIO mode (power from VDD instead of pin)?

To start the pulse counter program would need to look for repeating counter value to indicate end of pulse train to start counting  since sensor is always on.

**Comment by JoeyStrandnes** [comment]
Hi, 

Glad you like my Arduino driver!

I was considering adding that functionality in the beginning of the project but decided not to do so.
The reason was it only required an additional I/O-pin and does potentially take "much" longer time to complete the conversion. 
The ordinary "getTemp" time is 24ms for the ADC conversion and 11us for each pulse, usually ~12ms for room temperature, totaling ~35ms. 

A blocking function of up to 50ms to read the temperature from a sensor like this is significant in my opinion.
Adding the "free-running" mode would in worst case take 50% longer time to retrieve the value. 
Since you would have to discard the first pulse train if you happen to check the timer/counter during a transmission period. This might not really be a problem since you’re more likely to check the sensor during its ADC-conversion period. 

I do se a use case for a blocking free-running mode since it would save a I/O-pin. 
Il implement it later in the week when I have some free time.

I was thinking of adding an asynchronous component to this, either have it throw an interrupt if the temperature exceeded a user set limit and or by always having the latest temperature pulse count in memory and updating it freely from the main thread. I wasn’t able to figure out a way to achieve this without using an additional timer.
The ATMega328PB has too few timers so I couldn’t justify occupying two timers for a simple sensor like this.

**Comment by JoeyStrandnes** [comment]
Hi @bob-u,

I added the  free-running/ single GPIO mode, I've tested it and it seems to work on my machine with an Arduino Nano.
Mind testing it as well before I draft a new release? 

The updated code can be found in PR #3 

The code below is all that is needed to test the new feature out. 



```c++
#include "NST1001.h"


float Temperature{0};
const char Unit{'C'}; // The available units are Celsius(C), Fahrenheit(F) and Kelvin(K).

NST1001 nst1001(Unit);


void setup(){

  Serial.begin(115200);
  nst1001.init();


}



void loop(){

  Temperature = nst1001.getTemp();

  Serial.println("The temperature is: " + String(Temperature) + Unit);
  delay(1000);

}
```
